name: Test Runner

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: which tar || echo "tar not found"
      - run: tar --version || echo "tar command failed"
